### ISSUE TITLE
Editing Format

### ISSUE THREAD

**Issue by ki-li06** [Juoper/Timetable#5]
- _Diese Kurse fallen heute, am FRIDAY aus_ -> 'Diese Kurse fallen heute, am FRIDAY**, den 31.03.2023** aus**:**'
- _Kurs: 11 Ethik | 1eth3 | null_ -> removing ' **| null**'
- Alle Angaben ohne Gewähr. -> '_(Alle Angaben ohne Gewähr.)_'

(GitHub format broken)

**Comment by Juoper** [comment]
isn't working currently
